### ISSUE TITLE
Volunteer Task - Test Teach.Mozilla.org fork for Markdown Display

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#121]
If we go with a fork of the teach.mozilla.org fork , as I believe we will there are a couple of things we need to know better.   If someone has time to pick up a bit of research from me it would help this go faster.  

  I understand the code, and have things running on my local host, so I can take questions. If you get stuck with environment build, best is to research on the web, or ask for help in IRC from other webdevs.  
# Pre-requisites

Basic understanding of Github (pull requests) , web development, node and markdown.
# Participation Steps
1. Fork the develop branch of my fork  https://github.com/emmairwin/teach.webmaker.org/
2. Get it running locally as per README.md instructions
3. Help test for the conditions below (in what we need to know), leaving comments so we can be aware of your work and successes :)

**What we need to know**
- [x] How to pull in an entire markdown file from a remote address, and display as content. (see what we already know, to pickup where I left off)
- [x] If there will be styling challenges we need to accommodate (meaning when we pull in markdown how do things _look_)
- [x] Fix (converted from markdown) is displaying literally:
  ![2015-08-15_1718](https://cloud.githubusercontent.com/assets/60618/9291395/bd972e90-4371-11e5-8a8c-f816b5cc7c7c.png)

**What we already know**
We can use a node package with react to process strings of markdown.  
### More detail on environment
- Follow the instructions here: https://github.com/mozilla/teach.webmaker.org/blob/develop/README.md to get your localhost up and running, EXCEPT don't fork their copy, [fork my develop branch](https://github.com/emmairwin/teach.webmaker.org/tree/develop) .
- Once you have it up and running it should look like this (if the side menu is different you might have the wrong copy)
  ![full screen](https://cloud.githubusercontent.com/assets/60618/9291425/693cd85c-4373-11e5-9dea-c89e834e2b77.png)
- Understand the basic file structure:  pages are the 'pages' folder 'components' (like header, footer, side menu) are in the components folder.  You only need look in the page folder for moz-participation.jsx 
- You'll see a line:   var html = marked('I am using **markdown**.');   which is a the hard-coded markdown text displayed when you click on the Participation menu item.  THIS is where we need to test pulling in external markdown.
- This is the documentation for the [marked node module](https://github.com/emmairwin/marked/blob/master/README.md) to better understand how we can leverage it .
- Figure out how to pull the markdown [in this external document to that page](https://github.com/emmairwin/community_curriculum/blob/master/participation/design_thinking_for_participation/en/design_thinking_group.md).
  
  @SOFTowaha  has been trying to work on this, with environment issues.

**Comment by ioana-chiorean** [comment]
@alexlakatos what do u think of this? It screams your name.

**Comment by emmairwin** [comment]
There should be heart emoticons on github comments.  Thanks Ioana for thinking of connections!

**Comment by AlexLakatos** [comment]
I'll look into it over the weekend. Sounds right up my alley. :heart:

**Comment by asdofindia** [comment]
Since this issue is still open and since I wanted to learn how react and jsx works, I took the liberty of doing some research on it.

The markdown is rendered literally because [JSX escapes all data passed to it](https://facebook.github.io/react/docs/jsx-gotchas.html#html-entities) and can be fixed by using [dangerouslySetInnerHTML](https://facebook.github.io/react/tips/dangerously-set-inner-html.html) like thus:
![fix render](https://cloud.githubusercontent.com/assets/945777/9702489/2ff03312-547d-11e5-9fd7-0bf097b9e51c.jpg)

While **loading external files**, there is definitely two approaches (dunno if there're more). 

One is to pull the external content while `gulp`ing the website itself. (Probably as a git submodule). Then include content from it by reading them using something like `var content = fs.readFileSync('./submodule/design_thinking_group.md', 'utf8');`

Another way is to load them on the client side with an ajax request. This has the advantage that the external markdown can be updated without needing to render the website again. 

I do not know enough of how react works to do the second approach, but here's what external markdown files look inside that context (rendered in the first approach):
![external markdown read from file system](https://cloud.githubusercontent.com/assets/945777/9702509/eccdefd8-547d-11e5-922e-add1613bc7ce.png)

I shall send a PR if you like this.

**Comment by emmairwin** [comment]
@asdofindia !! You are always accomplish amazing things - sorry for the slow response I was away for a couple of weeks. Yes please send a PR and I'll do some testing!  Excited!

**Comment by emmairwin** [comment]
As a follow-up I have reached out to teach.mozilla.rg folks with our update, and questions about whether it makes sense to have a fork, or to merge our improvements into their version as a PR and discuss 'Participation' as a menu item there.   If that's not ideal, then our next steps will be to discuss theming colors for our fork- but from what I can see we are almost done this one  with some testing.  woot!  Looking forward to PR

**Comment by asdofindia** [comment]
@emmairwin I've sent the PR. It works properly only when a static site is generated (read the PR description). Therefore, it might be wiser to ask t.m.o folks for better ideas, yeah. Anyhow, if someone else wants to work where I left off refer the PR just above.

**Comment by emmairwin** [comment]
Thanks @asdofindia I asked you in the PR, but will ask here as well  - it was recommended that we use the https://github.com/chjj/marked    .  but what I think I'm reading is that marked won't work to import the contents, that has to be done through a different process, which is what you worked on?

**Comment by emmairwin** [comment]
For Akshay and anyone else interested in this - orginal example using marked from Pomax:  https://github.com/Pomax/gh-weblog/blob/develop/gh-weblog/components/MarkDown.jsx the stub I created used this but didn't reference a file.

**Comment by asdofindia** [comment]
The marked module can only process markdown strings passed to it. Therefore, yes, there has to be another process of pulling the file (either on the client side or on the server side). 

Right now what I've done is separate the markdown rendering functionality into [curriculum page](https://github.com/asdofindia/teach.webmaker.org/blob/markdown/pages/curriculum.jsx) (which definitely uses the marked module). This file corresponds to the stub you linked above. 

What we need is the other process - of pulling the file (either through a GET request to the markdown file sent from the user's browser or through reading the filesystem on the server)  

What I've tried to implement is the server reading the filesystem and serving the markdown rendered as html directly to the client when the client requests that URL. Since the client doesn't have access to the filesystem this is throwing errors in the console. (If anyone can tell me why react is doing the processing both on the server side and the client side, I'll be very happy. My hunch now is that this is because t.m.o has redundant capabilities [as written in the overview](https://github.com/mozilla/teach.webmaker.org#overview))

Gotta say there's a package called [react-markdown-file](https://github.com/adamrneary/react-markdown-file) which claims to pull in markdown file with a given filename. I think it relies on jquery to achieve this using a client side get request for the markdown file. This might be the solution we should pursue for.

_Another related (perfectionist) thing:_
There's a lot of code that'll be duplicated if we're creating new pages like this. As in, now, to create a new page, the [moz-participation.jsx](https://github.com/asdofindia/teach.webmaker.org/blob/markdown/pages/moz-participation.jsx) can be used as a template and with minimal copy paste we can have new pages. But even this goes against the concept of DRY. Ideally we should be able to just add/modify one or two lines of code to pull in a page from the curriculum to be served at a particular URL

**Comment by emmairwin** [comment]
@asdofindia Thanks for your explanation and agree on the duplication point.  That for each page we need to add update 3 items feels overkill, but I think that design choice is the Foundations and I'm not sure how far we want to deviate, unless there is someone interested in proposing a solution for the overall codebase that is (as a PR to main repo).  But so get your point...

**Comment by asdofindia** [comment]
I think I may have found something that works for me (ignoring the duplication part). I've updated [my PR](https://github.com/emmairwin/teach.webmaker.org/pull/1) to now do this:
- if fs.readFile is available (ie, we're on the server side), load the file from the filesystem.
- else: Put "Loading.." in the space where markdown should be
- in ComponentDidMount (which's executed only on the client side), use superagent (which's already in the package.json) to do an XHR to raw.githubusercontent.com/emmairwin/path-to-file and render the markdown into the space replacing "loading.."

Thanks to @Pomax from #webmaker for making me look at client side request.

**Benefits**
- Progressive enhancement: 
  - Even if javascript is turned off, the server will serve the markdown.
  - If javascript is on, the file is loaded via ajax thus giving a pleasant experience.

**Possible enhancements**
- Put a nice loading.gif spinner instead of "loading.."
- Error checking inside XHR response
- Add tests

**Comment by emmairwin** [comment]
Akshay you are a diamond thanks for getting to the bottom of that. I will merge and test on Friday. Thanks again super work

**Comment by emmairwin** [comment]
Awesome work akshay! Will sync on this when we're back from Athens
