### ISSUE TITLE
Prepare Onboarding Meeting For New Germany Contributors

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#185]
## Goal:

Initial logistic for meeting setup, and new contributors sent ‘Save The Date’ notification
## Success:

10 new contributors committed to attending the onboarding meeting
## Related Issues & Links:

Meta: #184
## Roles:

Owner: @brianking
Involved: @mariobehling
## Required:
- [ ] Finalise date for onboarding meeting (@mariobehling, [small], Due: Oct 21st)
- [ ] Send ‘Save The Date’ email to potential attendees (@mariobehling, [small], Due: Oct 23st)
- [ ] Secure venue and list basic logistical needs (@mariobehling, [medium], Due: Oct 27th)

**Comment by LucyeoH-zz** [comment]
Did this finish?

**Comment by mariobehling** [comment]
Current status
- We have a list of 20 people to invite and soft announced the dates
- Due to time constraints of team members, setting of definite date was postponed. The onboarding will now take place on two evenings (last week of Nov. and first week of Dec.)
- As for logistics we are planning to use the office as this give flexibility
- From the participation team Rosana Ardila and Mario Behling are confirmed

**Comment by brianking** [comment]
Thanks Mario.

I'll carry this one over to the next heartbeat.
