### ISSUE TITLE
[Open Task] Open is an Attitude

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#284]
# Workshop Curriculum

Looking for a workshop (just over an hour), that can teach Working Open - ready for the Leadership Summit on the 23rd/24th

Content suggestions welcome, but currently leaning towards some content based on [@clintlalonde 's Post 'Open is an Attitude'](http://clintlalonde.net/2012/10/18/open-is-a-noun-verb-adjective-and-an-attitude/) and [@openmatt 's Post 'How to Work Open'](http://openmatt.org/2011/04/06/how-to-work-open/) 

Using [story telling techniques](http://www.storyarts.org/lessonplans/lessonideas/) to recognize how Working Open lends to our success.  

Brief description of task.
- Propose Learning Outcomes   / Agree on Content (by Jan 8)
- Propose Draft (by Jan 15)
- Test in Singapore
## Prerequisite

Understanding of working open :)
Interest and background in developing learning content.
## Participation Steps

Steps can be collaborative between one or more people.   Please add your name and indicate which you are interested in helping with, so we can track and avoid duplicates.
1. Read both posts
2. Provide other content you think can lend to the success of a workshop on this topic (in comments)
3. Propose learning outcomes
4. Propose Draft Content for Review (by Jan 15)
5.  Tested in Singapore, and suggestions for improvement documented (@emmairwin )

Please use comments to ask questions if you / I'm sure you'll have a few questions!

**Comment by MajkenC** [comment]
At the engagement week I got to go to in Oct 2012, cbeard demonstrated the benefits of doing a call for feedback at the idea stage. I think this is an important concept because so much of what sucks for people working in the open is that they get almost done, and then get feedback. It never goes very well either people are upset they weren't consulted, or you missed people you should have consulted and need to start over.

There was an element of trying to reach out to stakeholders your work will affect to make sure you're collaborating effectively, but one of the lessons also was that people who you wouldn't think would be affected, might see a way to leverage your work, or see a roadblock you might have missed.

Also to riff on open is an attitude: that really gets to the concepts of "yes and..." and "love every idea for 5 minutes..." working open also means you need to be open to other people's ideas or remixing of your idea. You need to be collaborative. I think so many people are afraid of saying yes to bad ideas that they push back on the idea of being collaborative first. There's definitely a need to teach people that being open to ideas doesn't mean you're going to get sidetracked, and how to do it right.

**Comment by MajkenC** [comment]
Matt's post misses "accountability" as a goal of open. It's a complicated piece because it can turn into feeling like you're being held to the coals, but open is also meant to force you to follow your ideals, and to admit when you're getting something wrong - for the good of the project, not to be punitive. It also gives you authenticity when you are trying to convince people that you're doing something good. Embracing failure is a relevant skill to working in the open.

**Comment by CaptainCalliope** [comment]
I believe Matt's ideas have evolved a bit and he's been writing about them here: http://blog.workopen.org/

**Comment by LucyeoH-zz** [comment]
Emma - 
1. Does this have a volunteer or are you still looking? 
2. It looks like this will close (done or not) at the end of the heartbeat.

**Comment by emmairwin** [comment]
No volunteer -but my deck(under dev for the weekend) is linked here https://docs.google.com/presentation/d/1VpPdLaIDKqxF-FakiJ90wEFbFTyjiIfw2uPWfq6FG-4/edit#slide=id.g1068e7ee40_0_75
