### ISSUE TITLE
Continue momentum from the Leadership Summit

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#315]
## Success:
- ensure there’s follow up with all participants
- get all the initiatives started on the LS on github
- define next stages of support for the connected devices and campus campaign tracks
## Related Issues & Links:
# 
## Roles:

Owner: @rosanardila
Involved: @nukeador , @eirwin, @couci, @deimidis , Faye, @williamq 
Consulted: @geroter , 270, 
## Required:
- [x] Have a plan for follow up from coaches to all participants (@rosanardila @emmairwin , [medium], Due: Feb 10th)
- [x] Survey for participants is ready (@nukeador, @deimidis, [medium], Due: Feb 12th)
- [x] Email to all participants with link to survey and reminder for the Github issues (@nukeador, @deimidis,  [small], Due: Feb 12th)
- [x] Coaches reach out to all participants (@nukeador, @eirwin, @deimidis, Faye, [medium], Due: Feb 16th)
- [ ] LS participants have filed their github issues (coaches, [medium, Due: Feb 18th)
- [x] there's an analysis and assessment of the projects filed under the Participation- Leaders Repo (@rosanardila, @nukeador, @deimidis  [large] Due Feb 19th)

**Comment by rosanardila** [comment]
The GitHub Repo for the Leadership Summit Accountability already has 23 issues: 
https://github.com/mozilla/participation-leaders-accountability/issues.

We will send out an email to all participants with a link to the survey and a reminder to file issues on the Repo, we will then follow up with an email from coaches with a reminder. 

We will analyze the issues created until Feb 18th, so that we can craft a support plan for all projects in the next heartbeat. Part of that support plan are:
- The innovation Fund the Council is working on with the Connected Devices team
- The Campus Campaign phase 0 and general planning

**Comment by nukeador** [comment]
Survey and email draft almost ready.

**Comment by rosanardila** [comment]
Review of both survey and email done.

**Comment by rosanardila** [comment]
@nukeador, @deimidis: we can start analyzing the GitHub issues. As of now there are already 27 issues :)

**Comment by rosanardila** [comment]
part of the analysis would be to start tagging

**Comment by ioana-chiorean** [comment]
> @nukeador, @deimidis: we can start analyzing the GitHub issues. As of now there are already 27 issues :)

With 24 volunteers engaged/authors ( including @emmairwin 's one)

**Comment by rosanardila** [comment]
Emails sent, 35 issues open. Some might follow soon. Analysis will be updated here as short comments.

**Comment by deimidis** [comment]
Analysis after read [Github issues](https://github.com/mozilla/participation-leaders-accountability/issues):
- After create it, there were almost no updates on issues 
- That could be because lack of follow up from our team, and/or lack of clarity about next steps
- Until now, plans are for beginning Firefox Clubs or make them stronger
- Indonesia planning seems the most advanced one. 
- [CD] issues regarding CD are really vague, but changes after Singapore make difficult to advance on those ones
- There are some issues not related with CD or CC. Some of them were labeled «Community Sync». Those are related to Sync their communities about what happen on Singapore. No update after creation.
- Others are related to community projects not related with CC or CD like: WoMoz, MozVR, etc.
