### ISSUE TITLE
Guidelines for transition of Firefox OS events to CD events and outline key types of events we want to support/encourage

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#334]
## Goal:

Basic guidance available to publish
## Related Issues & Links:

[META] #327 
## Roles:

Owner: @williamq 
Involved: @brianking , @couci , @deimidis , @ensowhat 
## Required:
- [x] Initial stakeholders call (@williamq, [small], Due: Feb 10th) 
- [x] Draft plan, shared with stakeholders for feedback (@williamq @brianking @couci @deimidis @ensowhat, [medium], Due: Feb 16th)

**Comment by brianking** [comment]
Meeting scheduled for tomorrow.

**Comment by williamq** [comment]
The group tasked to come up with guidelines for transition of Firefox OS events to CD events met on February 17th and we concluded that it is too early to give specific guidance to people interested in running Firefox OS events and/or Connected Devices events. The reasons are two fold: 

1) we still need to wait for next steps for Firefox OS project to be crisper. Once this is done, it will be easier to articulate official guidelines and types of events we recommend/support. 

2) we feel more comfortable waiting for the “Bootstrap your Connected Device project” kit to be ready + the Reps Innovation Fund to be fully operational before providing official guidelines on the types of events we recommend/support. 

In the meantime, our recommendation is to stay in the holding pattern for now and ask the Council to clearly communicate to Reps that we are currently redefining our events strategy in order to better support the future of the Firefox OS project and Connected Devices, and that we’ll be providing new event guidelines soon.
