### ISSUE TITLE
Leadership toolkit draft and coaching cohort are ready

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#441]
## Objective Goal:

Leadership toolkit draft and coaching cohort are ready
- Responsible: @nukeador @deimidis
- Accountable: @nukeador
- Supporter: @couci, @verenanz1, @xellpher
- Consulted: @geroter 
- Informed: 

Supporting: [O2](https://docs.google.com/spreadsheets/d/1pR3DAlS32SB_RVBAM-595t4eXNU9fpWapwupQrQakYE/edit#gid=198884355) _"A focus set of relevant training and learning opportunities for mobilizers are systematized and they regularly access these opportunities to be more effective in their contributions and as a result providing more impact to Mozilla’s main initiatives."_
## Sub-Goal Success:
- [x] **Leadership toolkit:** Final draft for the toolkit content delivered (R: @nukeador @deimidis S: @verenanz1, @xellpher)
- [ ] **Leadership toolkit:** A place for hosting all content is in place. (R: @nukeador @deimidis)
- [ ] **Leadership toolkit:** Initial training plan is started (R: @nukeador @deimidis S: @verenanz1, @xellpher)
- [ ] **Coaching:** Our first cohort had 10h of training and are ready to received their first coachees. (R: @deimidis)
- [ ] **Coaching:** We received feedback from first Cohort and begin iteration (R: @deimidis)
## Related Issues & Links:
- [Reps planning repo](https://github.com/mozilla/Reps/issues)

**Comment by deimidis** [comment]
Leadership Toolkit: 
- Content is ready and we will begin to create the website in these days.
- Verena, Mikko, Greg and Guillermo will start to explore ways to teach this content (how to do it on offline meetings, etc)

Coaching Training:
- Slower than expected because of Guillermo's illness
- Training begun and we advance. 
- Council is beginning to work on deciding first coachees for this Coachs
