### ISSUE TITLE
A draft of the Community Participation Guidelines is recieving early feedback from community via Discourse and Activate Campaign

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#526]
## Objective Goal: 
 100 volunteer Mozillians have provided feedback on the draft Community Participation Guidelines

## Related documents and links 
* [Existing CPG](https://www.mozilla.org/en-US/about/governance/policies/participation/)

Discourse topic requesting feedback on the CPG, and is being actively guided by the D&I Participation working group.

Activate Campaign has been launched with each phase scheduled and understood.

## Item list:
- [x] Discourse text drafted, approved by @larissashapiro  and then posted. (R: @emmairwin)
- [x] Activate Campaign completed in markdown and submitted for PR (R: @emmairwin  )
- [x] Activate Campaign launched (R: @emmairwin @couci )
- [ ] 10 people have taken first steps to complete activate campaign (R: @emmairwin @couci)
- [x] Activate campaign call has been scheduled (R @emmairwin @couci :)

## Related Issues
[Reference meta issues and past issues] #

**Comment by emmairwin** [comment]
https://activate.mozilla.community/community-participation-guideline/

Feedback appreciated.  We have so far not  made the review - comments in the document, felt that the activity asked people to dive deeper into the meaning, purpose and potential of the CPG vrs reaction to words.

**Comment by couci** [comment]
I like this, some feedback:
I feel the intro is kind of big and confusing, personally I had to read it 2-3 times to get the full meaning. Can we make it shorter or bullet points? For the record I mean this one:
"Providing Mozilla’s global community the opportunity to review the 2.0 Community Participation Guidelines draft will provide critical feedback for Diversity & Inclusion at Mozilla as well as provide greater awareness to Mozilla’s communities of how the CPG supports healthy communities."
On the event flow, the face to face time is 1:1 with Larissa or scheduling time with Larissa and the community?
On the narrative part I would suggest a more direct ask. Instead of first explaining what narrative is and then request feedback, I would suggest to go on firstly: "in this face we would like to request your feedback on the form of a narrative. A narrative is..." In that way is more straight forward.

Hope feedback is helpful :)

**Comment by emmairwin** [comment]
Based on feedback from K and our team, the activity was cut back to be much simpler.
We also have scheduled a telegram and twitter chat on #mozillians AND a vidyo chat with Larissa to go where 'people are already talking'.
