### ISSUE TITLE
Create a Comprehensive Dashboard from Bitergia Data

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#559]
## Objective Goal: 
To create a nice dashboard that shows how we're doing against our goal of 1,500 new technical contributors while providing details of where those numbers are coming from. 

## User Story 

As a team leader I want to be able to easily see which programs/organizations are generating technical contributions for Mozilla over time. 

Therefore I want one location that I can go (and share) that shows: 
* How many technical contributions are being made from each organizations' members each month
* How many "first time to Mozilla's repos" are coming from each organization 
* Which Repos are each of the organization's people contributing to.

**Comment by LucyeoH-zz** [comment]
@geroter is there anything else you'd like to see on this dashboard considering that "contributors who aren't registered in any of our programs but are contributing to Mozilla" are already being tracked in an organization called "community".

**Comment by hmitsch** [comment]
Excellent request. @LucyeoH can you provide a napkin sketch for that dashboard? This will help align mental models and set expectations.

**Comment by LucyeoH-zz** [comment]
![image1](https://cloud.githubusercontent.com/assets/8070833/24922596/e3e27d98-1ebc-11e7-8cd8-4cd8cb4385b9.JPG)

@hmitsch here is my "napkin" sketch. I hope it makes sense it's definitely missing a bunch but will hopefully give a general idea of my thoughts.

**Comment by hmitsch** [comment]
Lucy, this is great. I will schedule a meeting for you & I to discuss this.

**Comment by hmitsch** [comment]
Meeting scheduled for tomorrow. Sorry for the late response.

**Comment by hmitsch** [comment]
## Questions to Bitergia
* Can we count the number for forks for a defined set of repos?
   * Example: Campus Clubs count a volunteer as "contributor" as soon as the repo https://github.com/mozillacampusclubs/Build-a-Virtual-World---examples is forked
* Waiting for Bitergia: Define Community Analytics *organizations* based on Github handles (instead of email addresses)
* Add https://github.com/mozillacampusclubs to Community Analytics

## Criteria to be counted as Contributor
* Campus Clubs: Fork a Campus repo
   * To be verified: Ask for email address of existing Club members
* Reps-recruited: Reps ask for email addresses during Reps events. This list then feeds into the *Reps-recruited* Community Analytics organization.
* Mozillians: Any type of activity on a specific set of repos we want to track

**Comment by hmitsch** [comment]
Moved to Backlog because of Bitergia's current focus on the _Contributor Research_.
