### ISSUE TITLE
Plan one Firefox for Android marketing initiative in India

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#99]
### Goal:

Bring local value and impact to Firefox for Android in India by initiating a volunteer community driven marketing campaign.

**Planning document is here:**
https://docs.google.com/document/d/1tvC-SXVpKYVdkJ8YqIIsaHHfjmZpQYUGOnD2QWCMDGo/edit?usp=sharing

**Reference:**
https://participation.etherpad.mozilla.org/fennec-india-team

**Objective:** Choose one campaign idea, and start building out team, scope and objectives

**Key result 1:** Marketing campaign idea chosen and supported by all stakeholders

**Key result 2:** Draft plan for campaign
### Success:

1) Consult with Community Marketing and bring them on board to help build out and execute the program.

2) Build volunteer leadership for the program

3) Initial goals and tactics of the campaign are documented
### Roles:

Owner: @brianking
Responsible: @brianking, @rosanardila 
Involved: @chelseanovak
Reviewer: @williamq, @debloper
### Required:
- [x] Initial meeting with Community Marketing (@brianking 1hr, Week ending Aug 7)
- [x] Weekly meeting setup and first meeting takes place (@brianking 1 hr, Week ending Aug 21)
- [x] Investigate if we can have a standalone APK for Marathi Firefox for Android that is updateable
- [ ] Dig up Android device penetration numbers, and Firefox marketshare numbers, for Marathi (@gueroJeff, @brianking 1 hour, Week ending Aug 21)
- [x] Initial goals and tactics of the campaign are documented (@brianking, @chelseanovak 2 hrs, Week ending Aug 21)

**Comment by brianking** [comment]
Status of standalone APK:

Talked to @rnewman about this who pointed me to [bug 1019724](https://bugzilla.mozilla.org/show_bug.cgi?id=1019724) which would enable this. It is close, will try to nudge it along. As for updates:

<quote>
http://ftp.mozilla.org/pub/mozilla.org/mobile/releases/latest/android-api-11/hi-IN/

so next it's about getting those users updates via our usual Balrog/updater infrastructure.

I see that our Nightly links point straight to https://ftp.mozilla.org, so perhaps no additional hosting is needed there, but you might need to chase someone down to make sure that we have CDN hosting for these builds in the region that you're targeting.
</quote>

The locale we want is Marathi (mr).

**Comment by chelseanovak** [comment]
Here is the beginnings of a marketing brief for this project: 
https://docs.google.com/document/d/1SdBrG4rxVJcpKcYqyoqdIirQecx1QwjMWZjWYReYtMA/edit

We need to get product information from Mike Han or whomever has the most relevant details on this for Marathi.

**Comment by brianking** [comment]
Marathi l10n team: https://wiki.mozilla.org/L10n:Teams:mr

Note that localizer does not equal marketer, so we'll have to determine who is interested in leading things on the ground. I talked with Chandrakant Dhutadmal and he is interested in getting started in earnest and helping getting other team members on board. I'll setup a meeting for this week.

**Comment by chelseanovak** [comment]
I'm on PTO Thursday and Friday, so early next week might work better for me.

**Comment by brianking** [comment]
Meeting with local team setup for 14:00 UTC on Monday.

**Comment by LucyeoH-zz** [comment]
Dig up Android device penetration numbers, and Firefox marketshare numbers, for Marathi - Blocked by Jeff Beatty (need to get directed to the right person) Will be moved to the next heartbeat. 
- Next HB: need to tap Jeff Beatty, look for other ways to get the numbers

**Comment by gueroJeff** [comment]
Sorry for the delay. Stay tuned here for more info: https://docs.google.com/spreadsheets/d/1w50tfhYd1YnL2ry0mbe_ONiIQ4PILPy4LAjc8Zs2Bag/edit#gid=0

As I explained to Brian, I began creating this list over a year ago when we were planning the Indic Fennec launch for 12 Indic locales (still the single largest l10n launch for Fennec ever).

As I'm going though and updating the list, I'm learning that it has become nearly irrelevent with the release of Android 5.0. Lollipop boasts localizations into 70 languages, including 9 Indic languages (if you include Nepali and Sinhala). Any device in India running 5.0 will have these preloaded and carriers/manufacturers will have them enabled for use. I make this distinction because it is often the case that an Android device will ship in a country, complete with support for all 70 localizations, but with a special XML file created by the carrier to filter the list of OS languages to only those localizations the carrier believes users will actually use. In India for Indic locales, this won't be a problem.

All this being said, the best way to interpret this list is as a glimpse into backwards compatibility for Marathi and other Indic languages. Many of these devices will not be upgraded to Android 5.0, but may still have local language support thanks to the efforts of the device manufacturer. Determining Android 5.0 market penetration in India will be critical to the success of this project. As I understand it, anyone from the Fennec team can look into these numbers through the Google Play Store developer interface (rnewman was the last person to show them to me). For the older devices listed here, getting a glimpse of marketshare distribution by device in India may be difficult and I'm honestly not aware of a way to do that.

Hope this helps. Let me know if you have further questions.
